import type { JobPosting } from '@/lib/queries'

/**
 * Mock jobs used by the design-system playground. Shape matches the real
 * `JobPosting` interface so the editorial components run through their full
 * rendering path.
 */
export const MOCK_JOBS: JobPosting[] = [
  {
    id: 'mock-1',
    title: 'Verpleegkundige IC (36u)',
    slug: 'verpleegkundige-ic-mock1',
    company_id: null,
    city: 'Doetinchem',
    state: 'Gelderland',
    zipcode: '7009 BL',
    street: 'Kruisbergseweg 25',
    latitude: null,
    longitude: null,
    employment: 'Vast',
    job_type: ['Fulltime'],
    salary: '€3.200 – €4.100',
    description: 'Als IC-verpleegkundige werk je op onze 12-bedsafdeling Intensive Care.',
    content_md: null,
    header_image_url: null,
    url: null,
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    end_date: null,
    created_at: new Date().toISOString(),
    seo_title: null,
    seo_description: null,
    education_level: 'HBO',
    career_level: null,
    categories: 'Zorg & Welzijn',
    working_hours_min: 36,
    working_hours_max: 36,
    company: {
      id: 'mock-co-1',
      name: 'Slingeland Ziekenhuis',
      slug: 'slingeland-ziekenhuis',
      logo_url: null,
      website: null,
      linkedin_url: null,
      description: null,
      city: 'Doetinchem',
      kvk: null,
      latitude: null,
      longitude: null,
      postal_code: null,
      street_address: null,
    },
  },
  {
    id: 'mock-2',
    title: 'Logistiek medewerker (fulltime)',
    slug: 'logistiek-medewerker-mock2',
    company_id: null,
    city: 'Zutphen',
    state: 'Gelderland',
    zipcode: null,
    street: null,
    latitude: null,
    longitude: null,
    employment: 'Vast',
    job_type: ['Fulltime'],
    salary: '€2.400 – €2.800',
    description: null,
    content_md: null,
    header_image_url: null,
    url: null,
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    end_date: null,
    created_at: new Date().toISOString(),
    seo_title: null,
    seo_description: null,
    education_level: 'MBO',
    career_level: null,
    categories: 'Logistiek',
    working_hours_min: 36,
    working_hours_max: 40,
    company: {
      id: 'mock-co-2',
      name: 'Bol.com Sorteercentrum',
      slug: 'bol-com',
      logo_url: null,
      website: null,
      linkedin_url: null,
      description: null,
      city: 'Zutphen',
      kvk: null,
      latitude: null,
      longitude: null,
      postal_code: null,
      street_address: null,
    },
  },
  {
    id: 'mock-3',
    title: 'Allround elektromonteur',
    slug: 'allround-elektromonteur-mock3',
    company_id: null,
    city: 'Groenlo',
    state: 'Gelderland',
    zipcode: null,
    street: null,
    latitude: null,
    longitude: null,
    employment: 'Vast',
    job_type: ['Fulltime'],
    salary: '€2.900 – €3.600',
    description: null,
    content_md: null,
    header_image_url: null,
    url: null,
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    end_date: null,
    created_at: new Date().toISOString(),
    seo_title: null,
    seo_description: null,
    education_level: 'MBO',
    career_level: null,
    categories: 'Techniek',
    working_hours_min: 40,
    working_hours_max: 40,
    company: {
      id: 'mock-co-3',
      name: 'Nedap',
      slug: 'nedap',
      logo_url: null,
      website: null,
      linkedin_url: null,
      description: null,
      city: 'Groenlo',
      kvk: null,
      latitude: null,
      longitude: null,
      postal_code: null,
      street_address: null,
    },
  },
  {
    id: 'mock-4',
    title: 'HR Business Partner',
    slug: 'hr-business-partner-mock4',
    company_id: null,
    city: 'Winterswijk',
    state: 'Gelderland',
    zipcode: null,
    street: null,
    latitude: null,
    longitude: null,
    employment: 'Vast',
    job_type: ['Fulltime'],
    salary: '€4.500 – €5.800',
    description: null,
    content_md: null,
    header_image_url: null,
    url: null,
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    end_date: null,
    created_at: new Date().toISOString(),
    seo_title: null,
    seo_description: null,
    education_level: 'HBO/WO',
    career_level: null,
    categories: 'HR',
    working_hours_min: 32,
    working_hours_max: 40,
    company: {
      id: 'mock-co-4',
      name: 'Koninklijke Swinkels Family',
      slug: 'swinkels',
      logo_url: null,
      website: null,
      linkedin_url: null,
      description: null,
      city: 'Winterswijk',
      kvk: null,
      latitude: null,
      longitude: null,
      postal_code: null,
      street_address: null,
    },
  },
]

/** Mock sector tiles. */
export const MOCK_SECTORS = [
  { name: 'Zorg & Welzijn', description: 'Ziekenhuizen, ouderenzorg, kinderopvang', count: 87 },
  { name: 'Techniek & Industrie', description: 'Maakindustrie, bouw, installatie', count: 64 },
  { name: 'Logistiek & Transport', description: 'Warehousing, chauffeurs, planning', count: 42 },
  { name: 'Retail & Horeca', description: 'Winkels, hospitality, catering', count: 31 },
  { name: 'Onderwijs', description: 'PO, VO, MBO en volwassenonderwijs', count: 24 },
  { name: 'Agro & Foodtech', description: 'Pluimvee, akkerbouw, voedingsindustrie', count: 14 },
]

/** Mock neighbourhoods. */
export const MOCK_NEIGHBOURHOODS = [
  { postcode: '7001', name: 'Centrum-Zuid', count: 47 },
  { postcode: '7002', name: 'Schöneveld', count: 28 },
  { postcode: '7004', name: 'De Huet', count: 19 },
  { postcode: '7007', name: 'IJsselzicht', count: 33 },
  { postcode: '7009', name: 'Lookwartier', count: 41 },
  { postcode: '7021', name: 'Zelhem', count: 22 },
]

/** Mock employer chips. */
export const MOCK_EMPLOYERS = [
  { name: 'Slingeland Ziekenhuis', count: 12, logoUrl: null },
  { name: 'Nedap', count: 8, logoUrl: null },
  { name: 'ROC Graafschap', count: 7, logoUrl: null },
  { name: 'Zozijn', count: 6, logoUrl: null },
  { name: 'Koninklijke Swinkels', count: 5, logoUrl: null },
  { name: 'Bol.com Zutphen', count: 4, logoUrl: null },
]
