// Generated by mcp__supabase__generate_typescript_types
// Run the type generation command to populate this file with actual database types.
//
// Placeholder types used by query helpers until real types are generated:

export type Database = Record<string, never>

/** Minimal job posting shape for query return types */
export interface JobPosting {
  id: string
  title: string
  slug: string | null
  company_name: string | null
  city: string | null
  state: string | null
  postal_code: string | null
  street_address: string | null
  country: string | null
  latitude: number | null
  longitude: number | null
  employment_type: string | null
  salary_min: number | null
  salary_max: number | null
  salary_currency: string | null
  salary_period: string | null
  description: string | null
  content_md: string | null
  url: string | null
  apply_url: string | null
  company_logo: string | null
  company_website: string | null
  company_linkedin: string | null
  company_kvk: string | null
  platform_id: string | null
  review_status: string | null
  published_at: string | null
  expires_at: string | null
  created_at: string
  updated_at: string | null
}

/** Platform / tenant record */
export interface Platform {
  id: string
  name: string
  slug: string | null
  domain: string | null
  primary_color: string | null
  logo_url: string | null
  hero_title: string | null
  hero_subtitle: string | null
  seo_description: string | null
  region_name: string | null
  province: string | null
  is_public: boolean
  is_master: boolean
  indexnow_key: string | null
  created_at: string
}

/** Saved job record */
export interface SavedJob {
  id: string
  user_id: string
  job_posting_id: string
  platform_id: string
  created_at: string
}

/** Job application log record */
export interface JobApplication {
  id: string
  user_id: string
  job_posting_id: string
  platform_id: string
  clicked_at: string
}
