/**
 * Draft preview route for pending/unpublished vacatures.
 *
 * Only accessible via HMAC-signed URLs generated by the admin.
 * Token expires after 1 hour. Always noindex/nofollow.
 */

import Image from 'next/image'
import { headers } from 'next/headers'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { getTenantById, getTenantByHostForPreview } from '@/lib/tenant'
import { getJobByIdForPreview } from '@/lib/queries'
import { verifyPreviewToken } from '@lokale-banen/shared'
import { TenantHeader } from '@/components/tenant-header'
import { Wegwijzer } from '@/components/wegwijzer'
import { JobDetail } from '@/components/job-detail'
import { ApplyButton } from '@/components/apply-button'
import { Footer } from '@/components/footer'
import { formatRelative } from '@/lib/utils'
import { slugifyCity } from '@lokale-banen/database'
import { AlertTriangle } from 'lucide-react'

interface PreviewPageProps {
  params: Promise<{ id: string }>
  searchParams: Promise<{ token?: string; platform?: string }>
}

// Always noindex — draft content, must never be public
export const metadata: Metadata = {
  robots: { index: false, follow: false, nocache: true },
  title: 'Draft Preview',
}

export default async function PreviewPage({ params, searchParams }: PreviewPageProps) {
  const { id } = await params
  const { token, platform } = await searchParams

  if (!token || !verifyPreviewToken(id, token)) notFound()

  // Tenant resolution for preview:
  // 1. If ?platform= query param is set, look up by ID (no filters)
  // 2. Otherwise, look up by host WITHOUT is_public filter (so freshly
  //    provisioned regio sites like apeldoornsebanen.vercel.app work)
  let tenant = platform ? await getTenantById(platform) : null
  if (!tenant) {
    const host = (await headers()).get('x-tenant-host')
    if (host) tenant = await getTenantByHostForPreview(host)
  }
  if (!tenant) notFound()

  const job = await getJobByIdForPreview(id)
  if (!job) notFound()

  const relatedJobs: [] = []
  const isExpired = job.end_date && new Date(job.end_date) < new Date()

  const citySlug = job.city ? slugifyCity(job.city) : null
  const postedAgo = job.published_at ? formatRelative(job.published_at) : null
  const endsInDays = job.end_date ? daysBetween(new Date(), new Date(job.end_date)) : null

  const wegwijzerItems: import('@/components/wegwijzer').WegwijzerItem[] = []
  if (job.city) {
    wegwijzerItems.push({
      id: 'city',
      label: job.city,
      icon: 'map',
      href: citySlug ? `/vacatures/${citySlug}` : undefined,
    })
  }
  if (postedAgo) {
    wegwijzerItems.push({ id: 'time', label: postedAgo, icon: 'clock' })
  }
  if (endsInDays !== null && endsInDays > 0 && endsInDays <= 30) {
    wegwijzerItems.push({ id: 'ends', label: `Nog ${endsInDays} dagen open`, icon: 'none' })
  }

  const statusLabel = job.published_at
    ? 'Live op publieke site'
    : job.review_status === 'approved'
      ? 'Goedgekeurd, nog niet gepubliceerd'
      : job.review_status === 'rejected'
        ? 'Afgekeurd / gearchiveerd'
        : 'In review (pending)'

  return (
    <div className="flex flex-col min-h-screen bg-surface">
      {/* DRAFT PREVIEW banner — persistent, impossible to miss */}
      <div
        role="alert"
        className="sticky top-0 z-50 bg-amber-500 text-black"
      >
        <div className="max-w-[1280px] mx-auto px-4 py-2 flex items-center gap-3 text-sm font-medium">
          <AlertTriangle className="h-4 w-4 shrink-0" aria-hidden="true" />
          <span className="flex-1">
            <strong>DRAFT PREVIEW</strong> — Dit is een voorbeeld voor admins. Status: {statusLabel}. Niet zichtbaar voor bezoekers.
          </span>
          <span className="text-xs opacity-75 hidden sm:inline">
            Preview link verloopt na 1 uur
          </span>
        </div>
      </div>

      <TenantHeader tenant={tenant} showSearch={false} />

      <Wegwijzer
        back={{ label: 'Overzicht', href: '/' }}
        items={wegwijzerItems}
      />

      <main className="flex-1 max-w-content mx-auto w-full py-6 px-4 lg:px-8 pb-24 sm:pb-8">
        {job.header_image_url ? (
          <div className="relative w-full aspect-[16/9] mb-6 overflow-hidden rounded-lg">
            <Image
              src={job.header_image_url}
              alt={job.title}
              fill
              priority
              sizes="(max-width: 1280px) 100vw, 1280px"
              className="object-cover"
            />
          </div>
        ) : (
          <div
            aria-hidden="true"
            className="relative w-full aspect-[21/9] mb-6 overflow-hidden rounded-lg"
            style={{
              background:
                'linear-gradient(180deg, transparent 60%, rgba(26,24,21,0.25) 100%), linear-gradient(135deg, var(--primary) 0%, var(--secondary, var(--primary-dark)) 100%)',
            }}
          />
        )}

        <JobDetail job={job} relatedJobs={relatedJobs} />
      </main>

      <Footer tenant={tenant} />

      <ApplyButton
        jobUrl={job.url}
        jobId={job.id}
        jobTitle={job.title}
        isExpired={!!isExpired}
      />
    </div>
  )
}

function daysBetween(a: Date, b: Date): number {
  const ms = b.getTime() - a.getTime()
  return Math.ceil(ms / 86_400_000)
}
